### ISSUE TITLE
Configure -> Custom CSS always empty in Redmine 3.4.0

### ISSUE THREAD

**Issue by martinvonwittich** [martin-denizet/redmine_custom_css#13]
Hi,

I've upgraded our Redmine staging instance to 3.4.0 today. The custom CSS plugin is still working - I can put custom CSS into the text box into the configuration, and it is saved to the database and included in every page. But after saving, the text box is immediately displayed empty again.

I've looked into the source and the problem seems to be in `app/views/settings/_custom_css.html.erb`. I'm not very experienced with Redmine development, but I've looked how other plugins access their settings, and I believe that `@settings[:css]` no longer works. The following change seems to solve the issue:

```
redmine.iserv.eu settings # diff -u /var/www/redmine{,-staging}/plugins/redmine_custom_css/app/views/settings/_custom_css.html.erb
--- /var/www/redmine/plugins/redmine_custom_css/app/views/settings/_custom_css.html.erb 2016-11-15 18:56:43.881838589 +0100
+++ /var/www/redmine-staging/plugins/redmine_custom_css/app/views/settings/_custom_css.html.erb 2017-07-20 15:42:34.158609309 +0200
@@ -14,7 +14,7 @@

 <p>
   <label><%= l(:label_cf_custom_css) %></label>
-  <%= text_area_tag 'settings[css]', @settings[:css] %>
+  <%= text_area_tag 'settings[css]', settings['css'] %>
   <em class="info"> <%= l(:help_cf_css) %></em>
 </p>
```

**Comment by virtualmarc** [comment]
I had the same issue and this fix worked, I create a pull request

**Comment by martin-denizet** [comment]
Fix published, thanks to the two of you!
