### ISSUE TITLE
white page after error

### ISSUE THREAD

**Issue by skollrc** [martin-denizet/redmine_custom_css#17]
Hi,

I tried to modify css for div class "footer" and the I can't access to my redmine. All pages are fully white. I removed custom_css plugin and everything goes well. When I tried to put it back, all pages become fully white again.

How can I solve the problem? Where is stored custom css parameters? 

best regards

**Comment by martin-denizet** [comment]
Hello, thanks for filling an issue.
Which version of Redmine were you using?
Would you have the log entry related to the crash also?
Cheers

**Comment by skollrc** [comment]
Redmine 3.4 (debian package). I resolve the problem by using mozilla debugging console. I juste erase bad css code and everything work fine now :-)
@+
