### ISSUE TITLE
licensing/copyright corrections

### ISSUE THREAD

**Issue by onlyjob** [martin-denizet/redmine_custom_css#4]
Please add copyright statement, something like

~~~~
Copyright 2013-2014 Martin DENIZET <myemail@github.com>
~~~~

and update licensing information. In particular version of the GPL-2 license needs to be clarified: did you license your work under GPL-2 license only or under GPL-2+ (including any later versions of GPL license)?

This is required to make your excellent plugin re-distributable and to allow its packaging for GNU/Linux distributions like [Debian](http://debian.org).

Besides you're re-distributing `libjs-codemirror` hence its licensing and copyright information should be documented as well. 

Also I'd like to note that `codemirror-compressed.js` is minified while its human-editable version is not included therefore it is the same as to distribute executable binary without sources. 

The following links may be of use to learn more about how to apply free software license:

 * http://www.producingoss.com/en/license-quickstart.html
 * http://opensource.org/faq#apply-license

Thank you.

**Comment by onlyjob** [comment]
Ping?

**Comment by martin-denizet** [comment]
Beleive it or not, I started to rework on all my plugins just yesterday :P
I started with redmine_login_audit but this one is definitively next, no kidding!

**Comment by onlyjob** [comment]
Great, thanks. Looking forward to try your improvements. :)

**Comment by onlyjob** [comment]
All good, thanks. :)
