### ISSUE TITLE
The page you were trying to access doesn't exist or has been removed.

### ISSUE THREAD

**Issue by Anton-Vedeneev** [martin-denizet/redmine_custom_css#6]
Hi Martin,
I Have installed redmine:
Environment:
  Redmine version                2.4.2.stable
  Ruby version                   1.9.3-p484 (2013-11-22) [x86_64-linux]
  Rails version                  3.2.16
  Environment                    production
  Database adapter               MySQL
SCM:
  Subversion                     1.8.8
  Mercurial                      2.8.2
  Git                            1.9.1
  Filesystem  
Redmine plugins:
  redmine_custom_css             0.1.4

I am having the problem, when click on configure http://pix.my/6587G2qX
the conclusion is http://pix.my/BzQEfiP8
from apache logs:
stderr: Missing template, responding with 404

I hope for Your help, thank you

**Comment by laurentelgard** [comment]
Please verify the plugin directory is correctly named "redmine_custom_css" :)

**Comment by martin-denizet** [comment]
You might be experiencing the same issue as #5 
I'm not able to reproduce the problem at the moment but maybe I will "blind-patch" it.

**Comment by martin-denizet** [comment]
Didn't get new reports of that issue, I assume this is not an issue anymore.
