### ISSUE TITLE
'git clone' command in the readme does not work

### ISSUE THREAD

**Issue by martinvonwittich** [martin-denizet/redmine_custom_css#8]
Hi,

I tried to install the plugin as described in the readme, but I got an error message:

<pre>
redmine /var/www/redmine # git clone git@github.com:martin-denizet/redmine_custom_css.git ./plugins/
fatal: destination path './plugins' already exists and is not an empty directory.
</pre>

But even when I specify a subdirectory, it still doesn't work:

<pre>
redmine /var/www/redmine # git clone git@github.com:martin-denizet/redmine_custom_css.git ./plugins/test
Cloning into './plugins/test'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
</pre>

This command worked for me:

<pre>
redmine /var/www/redmine/plugins # git clone 'https://github.com/martin-denizet/redmine_custom_css.git'         
Cloning into 'redmine_custom_css'...
remote: Counting objects: 121, done.
remote: Total 121 (delta 0), reused 0 (delta 0), pack-reused 121
Receiving objects: 100% (121/121), 230.10 KiB | 0 bytes/s, done.
Resolving deltas: 100% (45/45), done.
Checking connectivity... done.
</pre>

**Comment by martin-denizet** [comment]
Thank you, I will correct that!

**Comment by pifou42** [comment]
Same here.
Worked flawless using the same line as the Op

> git clone https://github.com/martin-denizet/redmine_custom_css.git
